name: brimomod

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Deploy to Server
        run: echo "Deploy step di sini, sesuaikan dengan kebutuhan (misal: rsync, scp, FTP, atau deploy ke layanan cloud)"
